export const ACCESS = {
  USER_MANAGEMENT: ["READ_ACCOUNTS"],
  USER_REGISTER: ["WRITE_ACCOUNTS"],
  SYSTEM_ADMIN: ["MANAGE_SYSTEM", "READ_ROLES", "READ_PERMISSIONS"],
  DEPARTMENTS: ["READ_DEPARTMENTS", "WRITE_DEPARTMENTS"],
  TEAM_PAGES: ["READ_TEAMS", "WRITE_TEAMS", "WRITE_OWN_TEAM_MEMBERS"],
  EMPLOYEES: ["READ_EMPLOYEES", "READ_ALL_EMPLOYEES"],
  HOLIDAYS: ["READ_HOLIDAYS", "WRITE_HOLIDAYS"],
  ANNOUNCEMENTS: ["READ_ANNOUNCEMENTS", "WRITE_ANNOUNCEMENTS"],
  PAYROLL_LIST: ["READ_PAYROLLS", "READ_ALL_PAYROLLS"],
  PAYROLL_ENGINE: ["WRITE_PAYROLLS"],
  ATTENDANCE_ADMIN: ["READ_ALL_ATTENDANCE", "WRITE_ATTENDANCE"],
  LEAVE_BALANCE: ["READ_LEAVE_BALANCES", "READ_ALL_LEAVE_BALANCES", "WRITE_LEAVE_BALANCES"],
  LEAVE_APPROVALS: ["APPROVE_ALL_LEAVES", "APPROVE_LEAVE_OVERRIDE", "READ_ALL_LEAVES"],
  OT_APPROVALS: ["READ_ALL_OTS", "MANAGE_SYSTEM"],
  HR_DASHBOARD: ["READ_HR_DASHBOARD"],
};

export const ACCESS_GROUPS = {
  ORGANIZATION: [
    ...ACCESS.DEPARTMENTS,
    ...ACCESS.TEAM_PAGES,
  ],
  HR_WORKSPACE: [
    ...ACCESS.EMPLOYEES,
    ...ACCESS.LEAVE_BALANCE,
    ...ACCESS.HOLIDAYS,
    ...ACCESS.ANNOUNCEMENTS,
  ],
  REQUEST_APPROVALS: [
    ...ACCESS.LEAVE_APPROVALS,
    ...ACCESS.OT_APPROVALS,
  ],
  PAYROLL_OPS: [
    ...ACCESS.ATTENDANCE_ADMIN,
    ...ACCESS.PAYROLL_LIST,
    ...ACCESS.PAYROLL_ENGINE,
  ],
  SYSTEM: [
    ...ACCESS.USER_MANAGEMENT,
    ...ACCESS.SYSTEM_ADMIN,
  ],
};
