export const ACCESS = {
  USER_MANAGEMENT: ["READ_ACCOUNTS"],
  USER_REGISTER: ["WRITE_ACCOUNTS"],
  SYSTEM_ADMIN: ["MANAGE_SYSTEM", "READ_ROLES", "READ_PERMISSIONS"],
  DEPARTMENTS: ["READ_DEPARTMENTS", "WRITE_DEPARTMENTS"],
  TEAM_PAGES: ["READ_TEAMS", "WRITE_TEAMS", "WRITE_OWN_TEAM_MEMBERS"],
  EMPLOYEES: ["READ_EMPLOYEES", "READ_ALL_EMPLOYEES"],
  HOLIDAYS: ["READ_HOLIDAYS", "WRITE_HOLIDAYS", "READ_SHIFTS", "WRITE_SHIFTS"],
  ANNOUNCEMENTS: ["READ_ANNOUNCEMENTS", "WRITE_ANNOUNCEMENTS"],
  PAYROLL_LIST: ["READ_PAYROLLS", "READ_ALL_PAYROLLS"],
  PAYROLL_ENGINE: ["WRITE_PAYROLLS"],
  ATTENDANCE_ADMIN: ["READ_ATTENDANCE", "READ_ALL_ATTENDANCE", "WRITE_ATTENDANCE"],
  LEAVE_BALANCE: ["READ_LEAVE_BALANCES", "READ_ALL_LEAVE_BALANCES", "WRITE_LEAVE_BALANCES"],
  LEAVE_APPROVALS: ["READ_LEAVES", "READ_ALL_LEAVES", "APPROVE_ALL_LEAVES", "APPROVE_LEAVE_OVERRIDE"],
  OT_APPROVALS: ["READ_OT", "READ_ALL_OTS", "MANAGE_SYSTEM"],
  HR_DASHBOARD: ["READ_HR_DASHBOARD"],
};

export const DATA_SCOPE_POLICIES = {
  EMPLOYEES: {
    own: "READ_MY_PROFILE",
    scoped: "READ_EMPLOYEES",
    all: "READ_ALL_EMPLOYEES",
    fullAccess: ["READ_ALL_EMPLOYEES", "WRITE_EMPLOYEES"],
  },
  ATTENDANCE: {
    own: "READ_MY_ATTENDANCE",
    scoped: "READ_ATTENDANCE",
    all: "READ_ALL_ATTENDANCE",
    fullAccess: ["READ_ALL_ATTENDANCE", "WRITE_ATTENDANCE"],
  },
  LEAVES: {
    own: "READ_MY_LEAVE",
    scoped: "READ_LEAVES",
    all: "READ_ALL_LEAVES",
    fullAccess: ["READ_ALL_LEAVES", "APPROVE_ALL_LEAVES", "APPROVE_LEAVE_OVERRIDE"],
  },
  LEAVE_BALANCES: {
    own: "READ_MY_LEAVE_BALANCE",
    scoped: "READ_LEAVE_BALANCES",
    all: "READ_ALL_LEAVE_BALANCES",
    fullAccess: ["READ_ALL_LEAVE_BALANCES", "WRITE_LEAVE_BALANCES"],
  },
  OVERTIME: {
    own: "READ_MY_OT",
    scoped: "READ_OT",
    all: "READ_ALL_OTS",
    fullAccess: ["READ_ALL_OTS"],
  },
  PAYROLLS: {
    own: "READ_MY_PAYSLIP",
    scoped: "READ_PAYROLLS",
    all: "READ_ALL_PAYROLLS",
    fullAccess: ["READ_ALL_PAYROLLS", "WRITE_PAYROLLS"],
  },
};

export const COMPATIBILITY_PERMISSION_ALIASES = [
  "RUN_PAYROLL",
  "READ_USER",
  "CREATE_USER",
  "UPDATE_USER",
  "DELETE_USER",
  "READ_LEAVE",
  "UPDATE_LEAVE",
  "APPROVE_LEAVE",
  "APPROVE_OT",
];

export const ACCESS_GROUPS = {
  ORGANIZATION: [
    ...ACCESS.DEPARTMENTS,
    ...ACCESS.TEAM_PAGES,
  ],
  HR_WORKSPACE: [
    ...ACCESS.EMPLOYEES,
    ...ACCESS.LEAVE_BALANCE,
    ...ACCESS.HOLIDAYS,
    ...ACCESS.ANNOUNCEMENTS,
  ],
  REQUEST_APPROVALS: [
    ...ACCESS.LEAVE_APPROVALS,
    ...ACCESS.OT_APPROVALS,
  ],
  PAYROLL_OPS: [
    ...ACCESS.ATTENDANCE_ADMIN,
    ...ACCESS.PAYROLL_LIST,
    ...ACCESS.PAYROLL_ENGINE,
  ],
  SYSTEM: [
    ...ACCESS.USER_MANAGEMENT,
    ...ACCESS.USER_REGISTER,
    ...ACCESS.SYSTEM_ADMIN,
  ],
};
